import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { seedContent, seedTemplates } from './seed.js';

const ROOT=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000);
const DB_FILE=path.resolve(process.env.DATA_FILE||'./data/database.json');
const APP_NAME=process.env.APP_NAME||'STIFIn Mulia Marketing Hub';
const SECURE=process.env.COOKIE_SECURE!=='false'&&process.env.NODE_ENV!=='development';
let state;

const status={
  content:['Belum dibuat','Draft','Sedang didesain','Perlu ditinjau','Siap dijadwalkan','Terjadwal','Dipublikasikan','Perlu diperbarui'],
  leads:['Baru','Sudah dihubungi','Terkualifikasi','Konsultasi','Booking','Tes selesai','Tindak lanjut','Belum siap','Tidak dilanjutkan'],
  promoters:['Calon','Belum tes','Sudah tes','Menunggu WSL 1','Selesai WSL 1','Menunggu WSL 2','Selesai WSL 2','Persiapan aktivasi','Promotor baru','Promotor aktif','Perlu pendampingan','Tidak aktif'],
  referrals:['Baru','Menunggu persetujuan','Diproses','Terhubung','Booking','Tes selesai','Selesai','Dibatalkan']
};
const defs={
  content:{label:'Bank Konten',single:'Konten',list:['code','title','pillar','format','plannedDate','status','owner'],search:['code','title','pillar','audience','hook','keyword'],fields:[
    ['code','Kode','text',1],['title','Judul','text',1],['pillar','Pilar','text',1],['category','Kategori'],['audience','Target pembaca'],['funnel','Tahap funnel','select',1,['Awareness','Consideration','Conversion','Retention']],['objective','Tujuan konten','textarea'],['format','Format','select',1,['Carousel','Reels','Image','Video','Story','Artikel','WhatsApp']],['channel','Kanal'],['problem','Masalah pembaca','textarea'],['hook','Hook','textarea'],['core','Inti penjelasan','textarea'],['action','Langkah praktis','textarea'],['caption','Caption siap pakai','textarea'],['carousel','Outline carousel','textarea'],['reels','Naskah reels','textarea'],['cta','CTA','textarea'],['keyword','Kata kunci SEO'],['hashtags','Hashtag','textarea'],['source','Sumber materi','textarea'],['plannedDate','Tanggal rencana','date'],['status','Status','select',1,status.content],['owner','PIC'],['designUrl','Tautan desain','url'],['publishedUrl','Tautan publikasi','url'],['reach','Jangkauan','number'],['saves','Disimpan','number'],['shares','Dibagikan','number'],['leads','Lead dari konten','number']]},
  leads:{label:'Lead dan Peserta',single:'Lead',list:['name','phone','city','type','source','status','nextFollowUp'],search:['name','phone','city','need','source','status'],fields:[
    ['name','Nama','text',1],['phone','Nomor WhatsApp','tel',1],['city','Domisili'],['type','Jenis lead','select',1,['Calon tes','Calon promotor','Peserta lama','Mitra','Lainnya']],['need','Kebutuhan','textarea'],['source','Sumber lead','select',0,['Instagram','Facebook','TikTok','WhatsApp Group','Google','Website','Rujukan','Kegiatan','Lainnya']],['sourceContent','Kode konten sumber'],['owner','PIC'],['status','Status','select',1,status.leads],['nextFollowUp','Tindak lanjut berikutnya','date'],['testSchedule','Jadwal tes','datetime-local'],['assignedPromoter','Promotor atau cabang'],['referralConsent','Persetujuan rujukan','select',0,['Belum','Ya','Tidak']],['serviceValue','Nilai layanan','number'],['notes','Catatan','textarea'],['lastContacted','Terakhir dihubungi','date']]},
  promoters:{label:'Promotor',single:'Promotor',list:['name','phone','city','status','wsl1','wsl2','testsThisMonth','nextReview'],search:['name','phone','city','status','barrier'],fields:[
    ['name','Nama','text',1],['phone','Nomor WhatsApp','tel'],['city','Domisili'],['status','Status','select',1,status.promoters],['tested','Sudah tes','select',0,['Belum','Sudah']],['testDate','Tanggal tes','date'],['wsl1','WSL 1','select',0,['Belum','Terjadwal','Selesai']],['wsl2','WSL 2','select',0,['Belum','Terjadwal','Selesai']],['activation','ID dan scanner','select',0,['Belum','Proses','Aktif']],['activationDate','Tanggal aktivasi','date'],['mentor','Pendamping'],['monthlyTarget','Target tes per bulan','number'],['testsThisMonth','Tes bulan ini','number'],['prospects','Prospek','number'],['bookings','Booking','number'],['contentPublished','Konten terbit','number'],['barrier','Hambatan utama','textarea'],['nextSupport','Dukungan berikutnya','textarea'],['nextReview','Tanggal review','date']]},
  referrals:{label:'Rujukan Wilayah',single:'Rujukan',list:['participantName','city','province','assignedPromoter','status','handedAt','result'],search:['participantName','phone','city','province','assignedPromoter','status'],fields:[
    ['participantName','Nama peserta','text',1],['phone','Nomor WhatsApp','tel'],['city','Kota atau kabupaten','text',1],['province','Provinsi'],['need','Kebutuhan','textarea'],['consent','Persetujuan','select',1,['Belum','Ya','Tidak']],['assignedPromoter','Promotor penerima'],['handedAt','Tanggal diserahkan','date'],['status','Status','select',1,status.referrals],['contactedAt','Tanggal dihubungi','date'],['result','Hasil'],['notes','Catatan','textarea']]},
  templates:{label:'Skrip WhatsApp',single:'Skrip',list:['code','situation','objective','body','active'],search:['code','situation','objective','body'],fields:[['code','Kode','text',1],['situation','Situasi','text',1],['objective','Tujuan'],['body','Template pesan','textarea',1],['active','Aktif','checkbox']]},
  users:{label:'Pengguna',single:'Pengguna',list:['name','email','role','active','createdAt'],search:['name','email','role'],fields:[['name','Nama','text',1],['email','Email','email',1],['role','Peran','select',1,['owner','admin','content','crm','viewer']],['active','Aktif','checkbox'],['newPassword','Password baru','password']]}
};
const labels={code:'Kode',title:'Judul',pillar:'Pilar',format:'Format',plannedDate:'Tanggal',status:'Status',owner:'PIC',name:'Nama',phone:'WhatsApp',city:'Domisili',type:'Jenis',source:'Sumber',nextFollowUp:'Tindak lanjut',wsl1:'WSL 1',wsl2:'WSL 2',testsThisMonth:'Tes bulan ini',nextReview:'Review',participantName:'Peserta',province:'Provinsi',assignedPromoter:'Promotor',handedAt:'Diserahkan',result:'Hasil',situation:'Situasi',objective:'Tujuan',body:'Pesan',active:'Aktif',email:'Email',role:'Peran',createdAt:'Dibuat'};
const permissions={owner:['*'],admin:['dashboard','calendar','content','leads','promoters','referrals','templates','reports','backup'],content:['dashboard','calendar','content','templates'],crm:['dashboard','leads','promoters','referrals','templates'],viewer:['dashboard','calendar','content','leads','promoters','referrals','templates']};
const loginAttempts=new Map();

initDb();

http.createServer(async(req,res)=>{
  try{
    headers(res);
    const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);
    const pathname=decodeURIComponent(url.pathname).replace(/\/+$/,'')||'/';
    if(pathname==='/health')return json(res,200,{ok:true});
    if(pathname==='/robots.txt')return text(res,200,'User-agent: *\nDisallow: /\n','text/plain; charset=utf-8');
    if(pathname.startsWith('/assets/'))return asset(pathname,res);
    if(pathname==='/login'){
      if(req.method==='GET')return html(res,200,login());
      if(req.method==='POST')return loginPost(req,res);
      return text(res,405,'Method not allowed');
    }
    const auth=getAuth(req);
    if(!auth)return redirect(res,'/login');
    const {user,session}=auth;
    if(req.method==='POST'){
      req.body=await body(req);
      if(!safe(req.body.csrf,session.csrf))return html(res,403,layout(user,session,'Akses ditolak','',messageView('Akses ditolak','Sesi formulir tidak valid. Muat ulang halaman.')));
    }
    if(pathname==='/logout'&&req.method==='POST'){res.setHeader('Set-Cookie',clearCookie());return redirect(res,'/login')}
    if(pathname==='/')return guard(res,user,session,'dashboard',()=>html(res,200,layout(user,session,'Dashboard','dashboard',dashboard())));
    if(pathname==='/calendar')return guard(res,user,session,'calendar',()=>html(res,200,layout(user,session,'Kalender Konten','calendar',calendar(url.searchParams.get('month')))));
    if(pathname==='/reports')return guard(res,user,session,'reports',()=>html(res,200,layout(user,session,'Laporan','reports',reports())));
    if(pathname==='/profile')return profile(req,res,user,session);
    if(pathname==='/backup.json')return guard(res,user,session,'backup',()=>download(res,DB_FILE,`stifin-mulia-backup-${today()}.json`,'application/json'));
    const exp=pathname.match(/^\/export\/(content|leads|promoters|referrals)\.csv$/);
    if(exp)return guard(res,user,session,'reports',()=>csv(res,exp[1]));
    const route=match(pathname);
    if(route)return resource(req,res,url,user,session,route);
    return html(res,404,layout(user,session,'Tidak ditemukan','',messageView('Halaman tidak ditemukan','Alamat yang dibuka tidak tersedia.')));
  }catch(e){console.error(e);if(!res.headersSent)html(res,e.statusCode||500,login(e.statusCode===413?'Data terlalu besar untuk diproses.':'Terjadi kendala pada aplikasi. Silakan coba kembali.'));else res.end()}
}).listen(PORT,'0.0.0.0',()=>console.log(`${APP_NAME} aktif pada port ${PORT}`));

function initDb(){fs.mkdirSync(path.dirname(DB_FILE),{recursive:true});if(fs.existsSync(DB_FILE)){state=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));normalize();return}const password=process.env.APP_ADMIN_PASSWORD||`SM-${crypto.randomBytes(9).toString('base64url')}`;if(!process.env.APP_ADMIN_PASSWORD)console.warn(`[SETUP] Password awal satu kali: ${password}`);state={meta:{version:1,appKey:process.env.APP_KEY||crypto.randomBytes(48).toString('base64url'),next:{users:2,content:121,leads:1,promoters:1,referrals:1,templates:17,activity:1}},users:[{id:1,name:'Pemilik STIFIn Mulia',email:String(process.env.APP_ADMIN_EMAIL||'admin@stifinmulia.com').toLowerCase(),role:'owner',passwordHash:hash(password),active:true,createdAt:new Date().toISOString()}],content:seedContent(),leads:[],promoters:[],referrals:[],templates:seedTemplates(),activity:[]};save()}
function normalize(){for(const k of ['users','content','leads','promoters','referrals','templates','activity'])state[k]??=[];state.meta??={};state.meta.next??={};state.meta.appKey??=process.env.APP_KEY||crypto.randomBytes(48).toString('base64url');for(const k of ['users','content','leads','promoters','referrals','templates','activity'])state.meta.next[k]??=Math.max(0,...state[k].map(x=>Number(x.id)||0))+1}
function save(){const tmp=`${DB_FILE}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(state,null,2));fs.renameSync(tmp,DB_FILE)}
function insert(k,r){const now=new Date().toISOString();const x={id:state.meta.next[k]++,...r,createdAt:r.createdAt||now,updatedAt:now};state[k].push(x);save();return x}
function update(k,id,r){const x=state[k].find(x=>Number(x.id)===Number(id));if(!x)return null;Object.assign(x,r,{updatedAt:new Date().toISOString()});save();return x}
function remove(k,id){const n=state[k].findIndex(x=>Number(x.id)===Number(id));if(n<0)return false;state[k].splice(n,1);save();return true}
function activity(user,action,subject,detail=''){state.activity.unshift({id:state.meta.next.activity++,userName:user?.name||'Sistem',action,subject,detail,createdAt:new Date().toISOString()});state.activity=state.activity.slice(0,1000);save()}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return `${s}:${crypto.scryptSync(String(p),s,64).toString('hex')}`}
function verify(p,v){if(!v?.includes(':'))return false;const[s,e]=v.split(':');const a=crypto.scryptSync(String(p),s,64),b=Buffer.from(e,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function token(user){const p={uid:user.id,csrf:crypto.randomBytes(24).toString('base64url'),exp:Math.floor(Date.now()/1000)+43200};const v=Buffer.from(JSON.stringify(p)).toString('base64url');return `${v}.${crypto.createHmac('sha256',state.meta.appKey).update(v).digest('base64url')}`}
function session(t){try{const[v,s]=String(t||'').split('.');const e=crypto.createHmac('sha256',state.meta.appKey).update(v).digest('base64url');if(!safe(s,e))return null;const p=JSON.parse(Buffer.from(v,'base64url'));return p.exp>Date.now()/1000?p:null}catch{return null}}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)))}
function getAuth(req){const s=session(cookies(req).stifin_session);if(!s)return null;const user=state.users.find(x=>Number(x.id)===Number(s.uid)&&x.active);return user?{user,session:s}:null}
function cookie(t){return `stifin_session=${encodeURIComponent(t)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=43200${SECURE?'; Secure':''}`}
function clearCookie(){return `stifin_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${SECURE?'; Secure':''}`}
function allowed(role,key){return permissions[role]?.includes('*')||permissions[role]?.includes(key)}

async function loginPost(req,res){const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0];let a=loginAttempts.get(ip)||{count:0,at:Date.now()};if(Date.now()-a.at>900000)a={count:0,at:Date.now()};if(a.count>=10)return html(res,429,login('Terlalu banyak percobaan. Tunggu 15 menit.'));const b=await body(req),email=String(b.email||'').trim().toLowerCase(),user=state.users.find(x=>x.email===email&&x.active);if(!user||!verify(b.password||'',user.passwordHash)){a.count++;loginAttempts.set(ip,a);return html(res,401,login('Email atau password tidak sesuai.',email))}loginAttempts.delete(ip);res.setHeader('Set-Cookie',cookie(token(user)));activity(user,'masuk ke','dashboard');return redirect(res,'/')}
async function profile(req,res,user,s){if(req.method==='GET')return html(res,200,layout(user,s,'Profil','',profileForm(user,s.csrf)));if(req.method!=='POST')return text(res,405,'Method not allowed');const b=req.body,name=String(b.name||'').trim();let error='';if(!name)error='Nama wajib diisi.';if(b.newPassword){if(!verify(b.currentPassword||'',user.passwordHash))error='Password saat ini tidak sesuai.';else if(String(b.newPassword).length<10)error='Password baru minimal 10 karakter.';else if(b.newPassword!==b.confirmPassword)error='Pengulangan password tidak sama.'}if(error)return html(res,422,layout(user,s,'Profil','',profileForm({...user,name},s.csrf,error)));const changes={name};if(b.newPassword)changes.passwordHash=hash(b.newPassword);update('users',user.id,changes);activity({...user,name},'memperbarui','profil');return html(res,200,layout({...user,name},s,'Profil','',profileForm({...user,name},s.csrf,'','Profil berhasil diperbarui.')))}

function match(p){const a=p.split('/').filter(Boolean),key=a[0];if(!defs[key])return null;if(a.length===1)return{key,mode:'list'};if(a.length===2&&a[1]==='new')return{key,mode:'new'};if(a.length===3&&/^\d+$/.test(a[1])&&a[2]==='edit')return{key,mode:'edit',id:+a[1]};if(a.length===2&&/^\d+$/.test(a[1]))return{key,mode:'save',id:+a[1]};if(a.length===3&&/^\d+$/.test(a[1])&&a[2]==='delete')return{key,mode:'delete',id:+a[1]};return null}
function resource(req,res,url,user,s,r){const d=defs[r.key];if(!allowed(user.role,r.key))return html(res,403,layout(user,s,'Akses ditolak','',messageView('Akses tidak tersedia','Peran akun Anda tidak memiliki izin.')));const readonly=user.role==='viewer';if(r.mode==='list'&&req.method==='GET'){const q=String(url.searchParams.get('q')||'').toLowerCase(),st=String(url.searchParams.get('status')||'');let rows=state[r.key].filter(x=>!q||d.search.some(k=>String(x[k]||'').toLowerCase().includes(q)));if(st)rows=rows.filter(x=>x.status===st);rows=[...rows].sort((a,b)=>b.id-a.id);const total=rows.length,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(pages,Math.max(1,+url.searchParams.get('page')||1));return html(res,200,layout(user,s,d.label,r.key,listView(r.key,d,rows.slice((page-1)*25,page*25),total,q,st,page,pages,user,s.csrf),url.searchParams.get('message')||''))}if(r.mode==='new'&&req.method==='GET'&&!readonly)return html(res,200,layout(user,s,`Tambah ${d.single}`,r.key,formView(r.key,d,{},s.csrf)));if(r.mode==='edit'&&req.method==='GET'){const x=state[r.key].find(x=>x.id===r.id);return x?html(res,200,layout(user,s,d.single,r.key,formView(r.key,d,x,s.csrf,[],readonly))):html(res,404,layout(user,s,'Tidak ditemukan','',messageView('Data tidak ditemukan','Data mungkin sudah dihapus.')))}if(readonly)return html(res,403,layout(user,s,'Akses ditolak','',messageView('Akses tidak tersedia','Akun viewer hanya dapat membaca data.')));if(r.mode==='list'&&req.method==='POST')return saveResource(res,user,s,r.key,d,null,req.body);if(r.mode==='save'&&req.method==='POST')return saveResource(res,user,s,r.key,d,r.id,req.body);if(r.mode==='delete'&&req.method==='POST'){const x=state[r.key].find(x=>x.id===r.id);if(!x)return redirect(res,`/${r.key}?message=Data+tidak+ditemukan`);if(r.key==='users'&&x.id===user.id)return redirect(res,'/users?message=Akun+yang+sedang+dipakai+tidak+dapat+dihapus');if(r.key==='users'&&x.role==='owner'&&state.users.filter(y=>y.role==='owner'&&y.active).length<=1)return redirect(res,'/users?message=Pemilik+aktif+terakhir+tidak+dapat+dihapus');remove(r.key,r.id);activity(user,'menghapus',d.single,x.title||x.name||x.participantName||x.code);return redirect(res,`/${r.key}?message=Data+berhasil+dihapus`)}return text(res,405,'Method not allowed')}
function saveResource(res,user,s,key,d,id,b){const existing=id?state[key].find(x=>x.id===id):null;if(id&&!existing)return html(res,404,layout(user,s,'Tidak ditemukan','',messageView('Data tidak ditemukan','Data mungkin sudah dihapus.')));const record={};for(const f of d.fields){const[n,,type]=f;if(n==='newPassword')continue;if(type==='checkbox')record[n]=b[n]==='on';else if(type==='number')record[n]=b[n]?Number(b[n]):0;else record[n]=String(b[n]||'').trim()}const errors=[];for(const f of d.fields)if(f[3]&&f[0]!=='newPassword'&&!record[f[0]])errors.push(`${f[1]} wajib diisi.`);if(key==='users'){record.email=record.email.toLowerCase();if(state.users.some(x=>x.email===record.email&&x.id!==id))errors.push('Email sudah digunakan.');if(!id&&String(b.newPassword||'').length<10)errors.push('Password minimal 10 karakter.');if(b.newPassword&&String(b.newPassword).length<10)errors.push('Password minimal 10 karakter.');if(existing?.role==='owner'&&record.role!=='owner'&&state.users.filter(x=>x.role==='owner'&&x.active).length<=1)errors.push('Peran pemilik aktif terakhir tidak dapat diubah.')}if(errors.length)return html(res,422,layout(user,s,d.single,key,formView(key,d,{...existing,...record,id},s.csrf,errors)));if(key==='users'&&b.newPassword)record.passwordHash=hash(b.newPassword);const x=id?update(key,id,record):insert(key,record);activity(user,id?'memperbarui':'menambahkan',d.single,x.title||x.name||x.participantName||x.code);return redirect(res,`/${key}?message=Data+berhasil+disimpan`)}

function login(error='',email=''){return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Masuk | ${esc(APP_NAME)}</title><link rel="stylesheet" href="/assets/app.css"></head><body class="login-body"><main class="login-card"><div class="login-logo">SM</div><p class="eyebrow">STIFIn MULIA</p><h1>Marketing Hub</h1><p class="muted">Pusat bank konten, calon peserta, promotor, dan jaringan layanan.</p>${error?`<div class="alert bad">${esc(error)}</div>`:''}<form method="post" class="stack"><label>Email<input type="email" name="email" value="${esc(email)}" required autofocus></label><label>Password<input type="password" name="password" required></label><button class="btn primary">Masuk ke Dashboard</button></form><p class="muted">Aplikasi internal. Tidak tersedia pendaftaran publik.</p></main></body></html>`}
function layout(user,s,title,active,content,flash=''){const nav=[['dashboard','/','Dashboard'],['calendar','/calendar','Kalender'],['content','/content','Bank Konten'],['leads','/leads','Lead dan Peserta'],['promoters','/promoters','Promotor'],['referrals','/referrals','Rujukan Wilayah'],['templates','/templates','Skrip WhatsApp'],['reports','/reports','Laporan'],['users','/users','Pengguna']].filter(x=>allowed(user.role,x[0]));return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(title)} | ${esc(APP_NAME)}</title><link rel="stylesheet" href="/assets/app.css"><script defer src="/assets/app.js"></script></head><body><div class="app"><aside class="sidebar"><a class="brand" href="/"><span class="brand-mark">SM</span><span><strong>STIFIn Mulia</strong><small>Marketing Hub</small></span></a><nav>${nav.map(x=>`<a class="nav ${active===x[0]?'active':''}" href="${x[1]}">${x[2]}</a>`).join('')}</nav><div class="foot"><a class="nav" href="/profile">Profil</a><form method="post" action="/logout"><input type="hidden" name="csrf" value="${s.csrf}"><button class="nav">Keluar</button></form></div></aside><main><header class="topbar"><button class="menu" data-menu>☰</button><div><small>Dashboard internal</small><h1>${esc(title)}</h1></div><div class="user"><span>${initials(user.name)}</span><div><strong>${esc(user.name)}</strong><small>${esc(user.role)}</small></div></div></header><section class="content">${flash?`<div class="flash">${esc(flash)}</div>`:''}${content}</section></main></div></body></html>`}
function dashboard(){const t=today(),statsData=[['Total Konten',state.content.length,'green'],['Dipublikasikan',state.content.filter(x=>x.status==='Dipublikasikan').length,'blue'],['Lead Masuk',state.leads.length,'orange'],['Booking',state.leads.filter(x=>x.status==='Booking').length,'green'],['Promotor Aktif',state.promoters.filter(x=>x.status==='Promotor aktif').length,'blue'],['Rujukan Aktif',state.referrals.filter(x=>!['Selesai','Dibatalkan'].includes(x.status)).length,'orange']];const upcoming=state.content.filter(x=>x.plannedDate>=t).sort((a,b)=>a.plannedDate.localeCompare(b.plannedDate)).slice(0,7),follow=state.leads.filter(x=>x.nextFollowUp&&x.nextFollowUp<=t&&!['Tes selesai','Tidak dilanjutkan'].includes(x.status)).slice(0,7);return `<div class="stats">${statsData.map(x=>`<article class="stat ${x[2]}"><span>${x[0]}</span><strong>${x[1]}</strong><small>Data saat ini</small></article>`).join('')}</div><div class="grid two"><section class="panel"><div class="panel-head"><div><p class="eyebrow">AGENDA</p><h2>Konten Mendatang</h2></div><a href="/calendar">Buka kalender</a></div>${items(upcoming,'content')}</section><section class="panel"><div class="panel-head"><div><p class="eyebrow">TINDAK LANJUT</p><h2>Perlu Dihubungi</h2></div><a href="/leads">Lihat semua</a></div>${items(follow,'leads')}</section></div><section class="panel"><p class="eyebrow">AKTIVITAS</p><h2>Aktivitas Terbaru</h2>${state.activity.length?`<div class="item-list">${state.activity.slice(0,12).map(x=>`<a><span>${dateShort(x.createdAt)}</span><div><strong>${esc(x.userName)} ${esc(x.action)} ${esc(x.subject)}</strong><small>${esc(x.detail||'')}</small></div></a>`).join('')}</div>`:empty('Aktivitas akan muncul setelah data diperbarui.')}</section>`}
function items(rows,key){return rows.length?`<div class="item-list">${rows.map(x=>`<a href="/${key}/${x.id}/edit"><span>${dateShort(x.plannedDate||x.nextFollowUp)}</span><div><strong>${esc(x.title||x.name)}</strong><small>${esc(x.pillar||x.need||x.type||'')}</small></div><span class="badge">${esc(x.status)}</span></a>`).join('')}</div>`:empty('Belum ada data terjadwal.')}
function listView(key,d,rows,total,q,st,page,pages,user,csrf){const edit=user.role!=='viewer';return `<section class="panel"><div class="panel-head wrap"><div><p class="eyebrow">DATA OPERASIONAL</p><h2>${d.label}</h2><small>${total} data ditemukan</small></div>${edit?`<a class="btn primary" href="/${key}/new">+ Tambah ${d.single}</a>`:''}</div><form class="filters"><input type="search" name="q" value="${esc(q)}" placeholder="Cari data"><select name="status"><option value="">Semua status</option>${(status[key]||[]).map(x=>`<option ${st===x?'selected':''}>${x}</option>`).join('')}</select><button class="btn">Terapkan</button></form><div class="table-wrap"><table><thead><tr>${d.list.map(x=>`<th>${labels[x]||x}</th>`).join('')}<th>Aksi</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr>${d.list.map(k=>`<td>${cell(k,x[k])}</td>`).join('')}<td class="table-actions"><a href="/${key}/${x.id}/edit">${edit?'Edit':'Lihat'}</a>${key==='leads'&&x.phone?`<a target="_blank" href="${wa(x.phone,`Assalamu’alaikum ${x.name||''}, saya dari STIFIn Mulia.`)}">WA</a>`:''}${key==='templates'?`<button type="button" data-copy="${esc(x.body)}">Salin</button>`:''}${edit?`<form method="post" action="/${key}/${x.id}/delete" data-confirm="Hapus data ini?"><input type="hidden" name="csrf" value="${csrf}"><button>Hapus</button></form>`:''}</td></tr>`).join(''):`<tr><td colspan="${d.list.length+1}">${empty('Belum ada data.')}</td></tr>`}</tbody></table></div>${pages>1?`<div class="pager">${page>1?`<a class="btn" href="/${key}?q=${encodeURIComponent(q)}&status=${encodeURIComponent(st)}&page=${page-1}">Sebelumnya</a>`:''}<span>Halaman ${page} dari ${pages}</span>${page<pages?`<a class="btn" href="/${key}?q=${encodeURIComponent(q)}&status=${encodeURIComponent(st)}&page=${page+1}">Berikutnya</a>`:''}</div>`:''}</section>`}
function formView(key,d,item,csrf,errors=[],readonly=false){return `<section class="panel narrow"><div class="panel-head"><div><p class="eyebrow">${item.id?'PERBARUI':'TAMBAH DATA'}</p><h2>${esc(item.title||item.name||item.participantName||item.situation||d.single)}</h2></div><a class="btn ghost" href="/${key}">Kembali</a></div>${errors.length?`<div class="alert bad"><ul>${errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<form class="form-grid" method="post" action="/${key}${item.id?`/${item.id}`:''}"><input type="hidden" name="csrf" value="${csrf}">${d.fields.map(f=>field(f,item[f[0]],readonly)).join('')}${readonly?'':`<div class="form-actions"><button class="btn primary">Simpan Data</button><a class="btn" href="/${key}">Batal</a></div>`}</form></section>`}
function field(f,value,readonly){const[n,label,type='text',required,options]=f,dis=readonly?'disabled':'',req=required?'required':'',full=type==='textarea'||['body','caption','carousel','reels'].includes(n)?'full':'';if(type==='textarea')return `<label class="${full}">${label}<textarea name="${n}" rows="${['body','caption'].includes(n)?8:4}" ${req} ${dis}>${esc(value||'')}</textarea></label>`;if(type==='select')return `<label>${label}<select name="${n}" ${req} ${dis}><option value="">Pilih</option>${options.map(x=>`<option ${String(value||'')===x?'selected':''}>${x}</option>`).join('')}</select></label>`;if(type==='checkbox')return `<label class="check"><input type="checkbox" name="${n}" ${value?'checked':''} ${dis}> ${label}</label>`;return `<label class="${full}">${label}<input type="${type}" name="${n}" value="${esc(value||'')}" ${req} ${dis}></label>`}
function calendar(month){month=/^\d{4}-(0[1-9]|1[0-2])$/.test(month||'')?month:new Date().toISOString().slice(0,7);const[y,m]=month.split('-').map(Number),first=new Date(Date.UTC(y,m-1,1)),last=new Date(Date.UTC(y,m,0)),before=(first.getUTCDay()+6)%7,cells=[];for(let i=0;i<Math.ceil((before+last.getUTCDate())/7)*7;i++){const d=i-before+1;if(d<1||d>last.getUTCDate())cells.push('<div class="day muted-day"></div>');else{const iso=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`,xs=state.content.filter(x=>x.plannedDate===iso);cells.push(`<div class="day"><b>${d}</b>${xs.slice(0,3).map(x=>`<a href="/content/${x.id}/edit">${esc(x.title)}</a>`).join('')}</div>`)}}const prev=new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7),next=new Date(Date.UTC(y,m,1)).toISOString().slice(0,7);return `<section class="panel"><div class="panel-head"><div><p class="eyebrow">RENCANA PUBLIKASI</p><h2>${month}</h2></div><div class="button-row"><a class="btn" href="/calendar?month=${prev}">Sebelumnya</a><a class="btn" href="/calendar?month=${next}">Berikutnya</a></div></div><div class="calendar"><div class="cal-head">${['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'].map(x=>`<span>${x}</span>`).join('')}</div><div class="cal-grid">${cells.join('')}</div></div></section>`}
function reports(){const group=(rows,k)=>Object.entries(rows.reduce((a,x)=>{const n=x[k]||'Belum diisi';a[n]=(a[n]||0)+1;return a},{})).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value),bar=rows=>{const max=Math.max(1,...rows.map(x=>x.value));return rows.length?`<div class="bars">${rows.slice(0,10).map(x=>`<div><p><span>${esc(x.label)}</span><b>${x.value}</b></p><i style="width:${Math.max(3,x.value/max*100)}%"></i></div>`).join('')}</div>`:empty('Belum ada data.')};const bookings=state.leads.filter(x=>['Booking','Tes selesai','Tindak lanjut'].includes(x.status)).length,tests=state.leads.filter(x=>x.status==='Tes selesai').length;return `<div class="stats"><article class="stat"><span>Rasio booking</span><strong>${pct(state.leads.length?bookings/state.leads.length:0)}</strong></article><article class="stat blue"><span>Rasio kehadiran</span><strong>${pct(bookings?tests/bookings:0)}</strong></article><article class="stat orange"><span>Konten terbit</span><strong>${state.content.filter(x=>x.status==='Dipublikasikan').length}</strong></article></div><div class="grid three"><section class="panel"><h2>Konten per Pilar</h2>${bar(group(state.content,'pillar'))}</section><section class="panel"><h2>Lead per Sumber</h2>${bar(group(state.leads,'source'))}</section><section class="panel"><h2>Tahap Promotor</h2>${bar(group(state.promoters,'status'))}</section></div><section class="panel"><h2>Unduh Data</h2><div class="button-row"><a class="btn" href="/export/content.csv">Konten CSV</a><a class="btn" href="/export/leads.csv">Lead CSV</a><a class="btn" href="/export/promoters.csv">Promotor CSV</a><a class="btn" href="/export/referrals.csv">Rujukan CSV</a><a class="btn primary" href="/backup.json">Cadangan lengkap</a></div></section>`}
function profileForm(user,csrf,error='',success=''){return `<section class="panel narrow"><p class="eyebrow">AKUN</p><h2>Profil dan Keamanan</h2>${error?`<div class="alert bad">${esc(error)}</div>`:''}${success?`<div class="flash">${esc(success)}</div>`:''}<form method="post" class="form-grid"><input type="hidden" name="csrf" value="${csrf}"><label>Nama<input name="name" value="${esc(user.name)}" required></label><label>Email<input value="${esc(user.email)}" disabled></label><label>Password saat ini<input type="password" name="currentPassword"></label><label>Password baru<input type="password" name="newPassword" minlength="10"></label><label>Ulangi password baru<input type="password" name="confirmPassword" minlength="10"></label><div class="form-actions"><button class="btn primary">Simpan Profil</button></div></form></section>`}
function messageView(t,p){return `<section class="panel narrow"><h2>${esc(t)}</h2><p>${esc(p)}</p><a class="btn" href="/">Kembali ke Dashboard</a></section>`}

async function body(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>1500000){const e=new Error('too large');e.statusCode=413;throw e}chunks.push(c)}return Object.fromEntries(new URLSearchParams(Buffer.concat(chunks).toString()))}
function safe(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y)}
function guard(res,user,s,key,fn){return allowed(user.role,key)?fn():html(res,403,layout(user,s,'Akses ditolak','',messageView('Akses tidak tersedia','Peran akun Anda tidak memiliki izin.')))}
function asset(p,res){const n=path.basename(p);if(!['app.css','app.js'].includes(n))return text(res,404,'Not found');res.setHeader('Cache-Control','public, max-age=3600');return text(res,200,fs.readFileSync(path.join(ROOT,'public',n)),n.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8')}
function headers(res){res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; form-action 'self'; frame-ancestors 'none'; base-uri 'self'");res.setHeader('X-Frame-Options','DENY');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cache-Control','no-store')}
function html(res,s,b){return text(res,s,b,'text/html; charset=utf-8')}function json(res,s,b){return text(res,s,JSON.stringify(b),'application/json')}function text(res,s,b,t='text/plain; charset=utf-8'){res.statusCode=s;res.setHeader('Content-Type',t);res.end(b)}function redirect(res,l){res.statusCode=303;res.setHeader('Location',l);res.end()}
function download(res,file,name,type){res.statusCode=200;res.setHeader('Content-Type',type);res.setHeader('Content-Disposition',`attachment; filename="${name}"`);fs.createReadStream(file).pipe(res)}
function csv(res,k){const rows=state[k],keys=[...new Set(rows.flatMap(Object.keys))].filter(x=>x!=='passwordHash'),e=v=>`"${String(v??'').replaceAll('"','""')}"`;res.statusCode=200;res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${k}-${today()}.csv"`);res.end('\ufeff'+[keys.map(e).join(','),...rows.map(r=>keys.map(k=>e(r[k])).join(','))].join('\r\n'))}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function cell(k,v){if(['status','role','format'].includes(k))return `<span class="badge">${esc(v||'-')}</span>`;if(k==='active')return v?'Aktif':'Tidak';const x=esc(v??'-');return x.length>100?`${x.slice(0,100)}…`:x}
function wa(p,m){return `https://wa.me/${String(p).replace(/\D/g,'').replace(/^0/,'62')}?text=${encodeURIComponent(m)}`}
function empty(t){return `<div class="empty">${esc(t)}</div>`}function initials(n){return String(n||'SM').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}function today(){return new Date().toISOString().slice(0,10)}function dateShort(v){if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',timeZone:'Asia/Jakarta'}).format(d)}function pct(v){return `${Math.round(v*100)}%`}
